export const siteConfig = {
    siteUrl: "https://www.tooonran.top",
    brand: "TooonRan",
    alternateBrand: "途然",
    title: "TooonRan 途然 — 个人主页",
    description: "TooonRan 途然的个人主页，记录代码、音乐、常用资源与持续更新的生活轨迹。",
    socialImage: "/images/tooonran-og.png",
    blogUrl: "https://blog.tooonran.top/",
    contactEmail: "tooonran@gmail.com",
    rssUrl: "https://blog.tooonran.top/rss2.xml",
    playlistId: "514347228",
    musicSource: {
        name: "juhe",
        scriptUrl: "https://raw.githubusercontent.com/pdone/lx-music-source/main/juhe/latest.js",
        endpoint: "/api/music-url",
        platform: "wy",
        quality: "320k",
    },
    hero: {
        coordinate: "36.6512° N · 117.1201° E",
        video: "/videos/hero.mp4",
        poster: "/images/hero-observatory.jpg",
        mottoLines: ["Explore the unknown,", "illuminate the possible."],
    },
    about: {
        avatar: "/images/avatar.jpg",
        skills: [
            { label: "Java", icon: "simple-icons:openjdk", color: "#e76f00" },
            { label: "Spring Boot", icon: "simple-icons:springboot", color: "#6db33f" },
            { label: "Vue", icon: "simple-icons:vuedotjs", color: "#42b883" },
            { label: "Redis", icon: "simple-icons:redis", color: "#dc382d" },
            { label: "摄影", icon: "lucide:camera", color: "#4f65ee" },
            { label: "音乐", icon: "lucide:music", color: "#ff695b" },
        ],
    },
    socials: [
        {
            label: "GitHub",
            href: "https://github.com/TheSummer001",
            icon: "simple-icons:github",
            color: "#181717",
        },
        {
            label: "Bilibili",
            href: "https://space.bilibili.com/350074542",
            icon: "simple-icons:bilibili",
            color: "#fb7299",
        },
        {
            label: "QQ",
            href: "tencent://AddContact/?fromId=50&fromSubId=All&SubCmd=CALL&uin=2026263245",
            icon: "simple-icons:qq",
            color: "#12b7f5",
        },
        {
            label: "Email",
            href: "mailto:tooonran@gmail.com",
            icon: "lucide:mail",
            color: "#ea4335",
        },
    ],
    resources: [
        {
            title: "开发工具",
            subtitle: "Build",
            items: [
                {
                    name: "GitHub",
                    url: "https://github.com",
                    desc: "代码托管与开放协作",
                    icon: "simple-icons:github",
                    color: "#181717",
                },
                {
                    name: "VS Code",
                    url: "https://code.visualstudio.com",
                    desc: "轻量、可扩展的代码编辑器",
                    icon: "simple-icons:visualstudiocode",
                    color: "#007acc",
                },
                {
                    name: "MDN",
                    url: "https://developer.mozilla.org",
                    desc: "可靠的 Web 开发参考",
                    icon: "simple-icons:mdnwebdocs",
                    color: "#1b1b1b",
                },
                {
                    name: "Can I use",
                    url: "https://caniuse.com",
                    desc: "前端特性兼容性速查",
                    icon: "lucide:badge-check",
                    color: "#d97706",
                },
            ],
        },
        {
            title: "设计工具",
            subtitle: "Shape",
            items: [
                {
                    name: "Figma",
                    url: "https://figma.com",
                    desc: "界面设计与原型协作",
                    icon: "simple-icons:figma",
                    color: "#f24e1e",
                },
                {
                    name: "Coolors",
                    url: "https://coolors.co",
                    desc: "快速生成配色灵感",
                    icon: "lucide:palette",
                    color: "#0066ff",
                },
                {
                    name: "Iconify",
                    url: "https://iconify.design",
                    desc: "统一检索开源图标",
                    icon: "simple-icons:iconify",
                    color: "#1769aa",
                },
            ],
        },
        {
            title: "日常工具",
            subtitle: "Keep",
            items: [
                {
                    name: "Notion",
                    url: "https://notion.so",
                    desc: "笔记、整理与协作",
                    icon: "simple-icons:notion",
                    color: "#000000",
                },
                {
                    name: "Excalidraw",
                    url: "https://excalidraw.com",
                    desc: "像手绘一样快速表达",
                    icon: "simple-icons:excalidraw",
                    color: "#6965db",
                },
                {
                    name: "DeepL",
                    url: "https://www.deepl.com",
                    desc: "自然流畅的翻译工具",
                    icon: "simple-icons:deepl",
                    color: "#0f2b46",
                },
            ],
        },
    ],
} as const;
